import Head from 'next/head';
import { useState } from 'react';

export default function Home() {
  const [error, setError] = useState(null);
  const [quantity, setQuantity] = useState(10);
  const [name, setName] = useState('');
  const [message, setMessage] = useState('');

  const presets = [1, 3, 5];
  return (
    <div>
      <Head>
        <title>Buy me a chai</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex'>
        <div></div>
        <div>
          <h1>Buy me a chai</h1>
          {presets.map((preset) => (
            <button key={preset} onClick={() => setQuantity(preset)}>
              {preset}
            </button>
          ))}
          <input
            type='number'
            name='price'
            id='price'
            onChange={(e) => setQuantity(parseFloat(e.target.value))}
          />

          <button>Donate ₹{quantity}</button>
        </div>
      </main>
    </div>
  );
}
